GET http://localhost:8080/

###

GET http://localhost:8080/api/ping
Accept: application/json

###

GET http://localhost:8080/not-found
Accept: application/json

###

POST http://localhost:8080/api/greet
Accept: application/json

{"name": ""}

###

POST http://localhost:8080/api/greet
Accept: application/json
X-User-Age: 80

{"name": "John"}

###

POST http://localhost:8080/api/hello/John/Doe
Accept: application/json