package problem

import (
	"fmt"
	"net/http"
)

// Problem is the struct definition of a problem details object
type Problem struct {
	// Type is a URI reference [RFC3986] that identifies the
	// problem type. This specification encourages that, when
	// dereferenced, it provide human-readable documentation for the
	// problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
	// this member is not present, its value is assumed to be
	// "about:blank".
	Type string `json:"type"`
	// Title is a short, human-readable summary of the problem
	// type.  It SHOULD NOT change from occurrence to occurrence of the
	// problem, except for purposes of localization (e.g., using
	// proactive content negotiation; see [RFC7231], Section 3.4).
	Title string `json:"title"`
	// Status is the HTTP status code ([RFC7231], Section 6)
	// generated by the origin server for this occurrence of the problem.
	Status int `json:"status,omitempty"`
	// Detail is a human-readable explanation specific to this
	// occurrence of the problem.
	// If present, it ought to focus on helping the client
	// correct the problem, rather than giving debugging information.
	Detail string `json:"detail,omitempty"`
	// Instance is a URI reference that identifies the specific
	// occurrence of the problem.  It may or may not yield further
	// information if dereferenced.
	Instance string `json:"instance,omitempty"`
	// Params are request input field level errors. They communicate
	// back to client hints as to the exact problem.
	Params map[string]string `json:"params,omitempty"`
}

// Error implements the error interface
func (pd *Problem) Error() string {
	if pd.Title == "" && pd.Detail == "" {
		return fmt.Sprintf("Status %d", pd.Status)
	}

	if pd.Detail == "" {
		return fmt.Sprintf("%s", pd.Title)
	}
	return fmt.Sprintf("%s: %s", pd.Title, pd.Detail)
}

// New creates a new Problem with given info.
func New(statusCode int, problemType, title, detail, instance string, params map[string]string) *Problem {
	// When this member is not present, its value is assumed to be
	// "about:blank".
	if problemType == "" {
		problemType = "about:blank"
	}

	// When "about:blank" is used, the title SHOULD be the same as the
	// recommended HTTP status phrase for that code (e.g., "Not Found" for
	// 404, and so on), although it MAY be localized to suit client
	// preferences (expressed with the Accept-Language request header).
	if problemType == "about:blank" {
		title = http.StatusText(statusCode)
	}

	return &Problem{
		Type:     problemType,
		Title:    title,
		Status:   statusCode,
		Detail:   detail,
		Instance: instance,
		Params:   params,
	}
}

// Status creates a new ProblemDetails error based just on the HTTP status code.
func Status(statusCode int) *Problem {
	return New(statusCode, "", "", "", "", nil)
}

// Unexpected will create a new problem for unexpected errors.
func Unexpected(err error) *Problem {
	return New(http.StatusInternalServerError, "unexpected", "Unexpected problem",
		err.Error(), "", nil)
}

// NotFound will create a new problem for when the record is not found.
func NotFound() *Problem {
	return New(http.StatusNotFound, "not-found", "Record not found",
		"", "", nil)
}

// NotPermitted will create a new problem for when the user is forbidden access.
func NotPermitted(username string) *Problem {
	detail := fmt.Sprintf("%s does not have proper permissions", username)
	return New(http.StatusForbidden, "not-permitted", "User not permitted",
		detail, "", nil)
}

// BadRequest will create a new problem for reqeust marshalling errors.
func BadRequest(err error) *Problem {
	return New(http.StatusBadRequest, "bad-request", "Bad or malformed request",
		"Fix the error and try again", "", nil)
}

// Validation will create a new problem for when request has field validation errors.
func Validation(params map[string]string) *Problem {
	return New(http.StatusBadRequest, "validation", "Validation failed",
		"Fix the errors and try again", "", params)
}

// RuleViolated will create a new problem for when a business rule is violated.
func RuleViolated(rule string) *Problem {
	return New(http.StatusBadRequest, "rule-violated", "Rule violated",
		rule, "", nil)
}

// NotCurrent will create a new problem for optimistic concurrency errors.
func NotCurrent() *Problem {
	return New(http.StatusConflict, "not-current", "Record not current",
		"Reload and try your changes again", "", nil)
}
